### ISSUE TITLE
FastCopy2.ini is overwriten on update

### ISSUE THREAD

**Issue by Meche697** [FastCopyLab/FastCopy#116]
I think this falls under a "bug".
Whenever I update the software (portable version), the FastCopy2.ini gets replaced and my stored Jobs are cleared
This happened on both Windows 10 and 7. INI should be created if it's not there and skipped if it is.

**Comment by shirouzu** [comment]
Sorry, I don't know about portable version, please use official version.
If you find the bug in official version, please use this format.
https://github.com/FastCopyLab/FastCopy/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by Meche697** [comment]
This IS off the official download. I extracted the files (not installed) when I opened the program, it overwrote my ini file.

**Comment by ghost** [comment]
I had this once in the past, too.
I guess that FC has a strict test for the ini-file to comply with the _current_ version. If some features were added or removed the ini-file seems to be considered invalid and is therefore replaced instead of being corrected.
I would suggest to either compare your ini-file with a fresh one and fix the differences (missing key-value pairs). Or start over with a fresh one in the first place. It should then no longer be replaced on minor updates until again some features are added or removed. As big changes to FC are rare, it might work for quite some time.
