### ISSUE TITLE
 "Listing+V", add verifyInfo AltStream?

### ISSUE THREAD

**Issue by TonyLeps** [FastCopyLab/FastCopy#162]
Shirouzu san, thank you so much for FastCopy. It is extremely powerful and helpful. I am grateful.

"Listing+V" is very helpful for verifying two directories. Is it possible to write verifyInfo (AltStream(:fc_verify) with hashinfo) to verified files of the DestDir, similiar to when files are copied?

Thank you again for your help.

**Comment by JCj8LDUz** [comment]
Please accept all my thanks to your excellent FastCopy software.

I'm essentially using the command line to create daily scheduled backup tasks.

The first issue I've been facing is that fc.exe doesn't raise any error flag (Thru ERRORLEVEL) if it detects an error in the parameters or before it creates a log file. The only way I found to get around it was to check for the presence of the log in my scripts.

Now, I have a detailed log with 50,436 file entries where the summary says:
Result : (ErrFiles : 1 / ErrDirs : 0) at 2023/03/12 09:02:06
Is there any way to identify the only file in error?

Lastly, FC sometimes does hang unexpectedly. In such instances the log only show the header, like:
=================================================
fcp(ver4.2.2 (Admin)) start at 2023/03/12 01:30:51
<Source>  C:\Users\Admin\Documents\*.*
<DestDir> E:\_Backups\Data\Admin\BkUp_2023-03-12_01-30\Documents\
<Exclude> XYZ\
<Command> Copy (Overwrite) (with Verify)
-------------------------------------------------

And nothing else.

But FC doesn't stop or raise any error flag. So the scheduled task aborts because of allocated time exceeded.

That does happen randomly and if the script is launched manually, it works.

Do you have any idea of why such thing happens, and what kind of information would you need to identify the problem?

Thank you for your attention on the matter and for developing such high quality software.

**Comment by shirouzu** [comment]
At the moment, that is not possible.
I will consider it.

P.S JCj8LDUz-san, please create independent issues.
