### ISSUE TITLE
I hope to help improve Chinese translation

### ISSUE THREAD

**Issue by lhy2871** [FastCopyLab/FastCopy#202]
**Question**
I found that the official Chinese version has been released.
But there are some translation errors.
I can provide assistance.
What is the method to submit my translated version now?

**Remarks**
My E-mail: lhy2871@126.com
Hanyuan Liu

**Comment by shirouzu** [comment]
Thank you very much for your suggestion.
It would be greatly appreciated if you could write to this issue with examples of correct translations.

**Comment by lhy2871** [comment]
eg. help->'check updates' should be "检查更新" instead of "确认更新", 'support fourm' could be "打开支持论坛网页", 'latest version' could be "最新版本下载地址".
Option->'post-process' should be "任务结束后运行" or "任务结束后...", 'normal' could be "默认"
Main window 'Estimate' could be "剩余时间"
Main Settings->Defaluts 'Estimate' could be "剩余时间"
Main window and Main Settings->Defaluts 'verify' should be "校验"
Main window and Main Settings->Defaluts 'Wipe & Delete...' could be "安全删除 (仅对删除模式生效，覆盖后删除，使文件不可被恢复，比正常模式慢)"
Main Settings->Verify options->verify mode 'Convertional verify (Check Dest Only)' should be "正常校验 [只校验传输后的文件(夹)]", 'Perfact...' should be "完美校验 [对源文件和传输后文件都进行校验]"
Main Settings->misc settings  'update check at start up' should be "启动时检查更新", 'Balloon Notification...' should be "完成后弹出气泡通知(窗口最小化时生效)"

Hanyuan

**Comment by shirouzu** [comment]
Thank you for pointing this out.
I would like to improve the Chinese version.
(I use DeepL Pro and Google translater, but I don't know Chinese language very well.)

However, as a prerequisite, please keep in mind the following restrictions

1. FastCopy's main screen often uses abbreviations. (This is due to the small screen size.)
   Ex) "Predicting/Estimating completion time" → "Estimate"

2. FastCopy's original text is Japanese. So the descriptions in the English version are sometimes inaccurate.
   Ex) "Wipe & Delete" is English version text, but "復元防止" is Original Japanese version text.

3. I want to refine Chinese string as literal translation (not free translation) from Original Japanese text.
   Ex) "復元防止" → "防止复原"（But I don't know that "防止修复" is more better or not）


> 'check updates' should be "检查更新" instead of "确认更新"

Thank you. I will modify it.


> 'support fourm' could be "打开支持论坛网页"

I think it could be just '支持论坛', because Japanese ver: "サポート掲示板" and English ver: "Support Forum".
(It doesn't contain "open" and "page")


> 'latest version' could be "最新版本下载地址"

I think it could be just '最新版本', because Japanese ver: "最新版" and English ver: "Latest version".
(It doesn't contain "download")


> 'post-process' should be "任务结束后运行" or "任务结束后..."

Current string is "任务结束后处理".
Process(JP:処理) means '处理', doesn't it?
And I feel "运行" is "run/running" (JP:実行).
Is "Process" called "运行" in Chinese?


> 'normal' could be "默认"

Hum...English ver is "normal"(like "standard") and Japanese is "標準", and it is not "default".
But I don't know "标准" is wrong or not.


> 'Estimate' could be "剩余时间"

I feel that "剩余时间" means "remaining time" (not "estimating time"), doesn't it?
And "Estimate"(JP:予測) is abbreviations. (It doesn't contain "time"(時間))


> 'verify' should be "校验"

Current string is "验证".
What is the difference between "验证" and "校验"?

DeepL and Google translater says...
 验证: Verification/Verify
 校验: Calibration/Check

So I feel "验证" is more better for "Verify" than "校验", Is this wrong?


> 'Wipe & Delete...' could be "安全删除 (仅对删除模式生效，覆盖后删除，使文件不可被恢复，比正常模式慢)"

Hum... Origial Japaese text is "復元防止", so I choose "防止复原". Is it wrong?
I want to "(仅对删除模式生效，覆盖后删除，使文件不可被恢复，比正常模式慢)" 
I will consider it.


> 'Convertional verify (Check Dest Only)' should be "正常校验 [只校验传输后的文件(夹)]"
> 'Perfact...' should be "完美校验 [对源文件和传输后文件都进行校验]"

"正常" is my mistake, "传统" is correct, I will fix it in the next version.

I will modify it to "传统验证（仅检查Dest）" and "完美验证（检查Src/Dest）".  (I prefer short expressions.)
I assume that most Chinese can understand basic English (like Pro/Source/Destination/Verify etc), am I wrong?


> 'update check at start up' should be "启动时检查更新"

Thank you. I will modify it.


'Balloon Notification...' should be "完成后弹出气泡通知(窗口最小化时生效)"

I search Windows API, I found "Balloon Notification" meas "气泡'提示'", so "完成后弹出气泡提示" is correct?
In the help/dialog, "完成" and "结束" are mixed up, which is not good, but I am not sure which way we should unify.

Sorry, "(窗口最小化时生效)" means "at minimized", but Japanese Original text is "（タスクトレイ格納時）".
It means "When stored in the task tray", so I think "(当存储在任务盘中时)" is not wrong, am I wrong?


Anyway, thank you very much for all your suggestions!
(And Chinese language is difficult for me...)

**Comment by AaronHzy** [comment]
'Estimate' should be "预计"（”预计“mean a prior estimation or calculation）

'verify' should be "校验"（”校验“mean a method of correcting data errors used during data transmission）

**Comment by shirouzu** [comment]
Thank you for your suggestion.

> 'Estimate' should be "预计"（”预计“mean a prior estimation or calculation）

Current string is "预估".
Could you tell me what is the difference between "预估" and "预计"?

> 'verify' should be "校验"（”校验“mean a method of correcting data errors used during data transmission）

Hum... FastCopy's verify does not have a "correction" function, only calculate hash values and compare it.
Still, would "校验" be more appropriate?

**Comment by lhy2871** [comment]
Thank you for taking my suggestion seriously！
Well, I understand that '预计' and '预估' are the same meaning.
And I understand that '校验' means comparing target with source and using a certain method to determine if they are consistent.

Hanyuan

**Comment by lhy2871** [comment]
I found that the email was not sent successfully. Sorry for not delivering the message in time.

Hi SHIROUZU
I understand you ofthuse abbreviations and want literal translation. I will try to give you strings that more accurate and use literal translate.

First of all, I think we could confirm the following modifications：
1、确认更新
2、支持论坛
3、最新版本
4、启动时检查更新

Let’s discuss:
1、Process(JP:処理) means '处理', doesn't it?
    A: Yes. But "处理" more often translate into ‘handle’. So I don't think “处理" should be used here. I will try to find another string.

2、"Hum...English ver is "normal"(like "standard") and Japanese is "標準", and it is not "default".
But I don't know "标准" is wrong or not.”
    A: I see. Let's use the word "标准” here.

3、"I feel that "剩余时间" means "remaining time" (not "estimating time"), doesn't it?”
    A: Yes, it means remaining time. If you want to express ‘prediction’ here. I suggest using "预估时间”.
       The meaning of 预测 is closer to forecast or prediction. More often used in unpredictable things, the results are generally unreliable.

4、验证：test and verify; checking; proving; testing; confirmation; corroboration; inspection; verification 
    校验：verification; check; proof; proof test; testing; inspection; checking
    Their meanings are very similar. The word 验证 is usually paired with true or false, always means check if it is genuine or fake. Does not contain the meaning of comparison.
    While 校验 is generally paired with accuracy, means "check accuracy”. 
    So I think 校验 is better.

5、"防止复原”, There is no such expression in Chinese. I prefer 防止被恢复.

6、传统 is fine! Yes, we could understand basic English. Personally, I prefer 100% translation. I have a bit of OCD(obsessive-compulsive disorder), haha. Never mind, let's use "传统验证（仅检查Dest）" and "完美验证（检查Src/Dest）”.

7、"完成后弹出气泡提示” is correct. Buy “气泡提示” , is a "Microsoft’s Chinese Translation” or "Apple’s Chinese Translation”. Correct, but we do not use normally.
    I think it is fine. And I cannot provide a better translation either.
    "完成" and “结束”  both can be used in this scenario, let's not change it for now, let me think about it again.

    The "(窗口最小化时生效)”  translation is not accurate enough. I prefer ”最小化到系统托盘时生效”. 
    In Microsoft’s Chinese, they translate 'task tray' into "系统托盘".

Thank you for valuing Chinese translation！
By the way, Japaneseis difficult for me… haha!
Have a nice weekend!

Hanyuan

**Comment by shirouzu** [comment]
> First of all, I think we could confirm the following modifications：
> 1、确认更新
> 2、支持论坛
> 3、最新版本

Yes, thank you!

> 4、激活时检查更新

I noticed that I used the word "激活" to mean license activation.
So I want to modify it to "启动时检查更新", is it wrong?

> A: Yes. But "处理" more often translate into ‘handle’. So I don't think “处理" should be used here. I will try to find another string.

I understood. I will modify "处理" to "运行".

> So I think 校验 is better.

I understood. I will modify "验证" to "校验".

> 5、"防止复原”, There is no such expression in Chinese. I prefer 防止被恢复.

Oh...I understood. I will modify "防止复原" to "防止被恢复".

> The "(窗口最小化时生效)”  translation is not accurate enough. I prefer ”最小化到系统托盘时生效”. 
> In Microsoft’s Chinese, they translate 'task tray' into "系统托盘".

I understood. I will modify it.

Thank you very much for all your suggestions!

P.S
> I prefer 100% translation

Yes, I feel it is not only you, but most Chinese people prefer 100% translation.
(In Japan, especially English IT terms are expressed using English or its katakana(phonetic notation) letters.)

> By the way, Japaneseis difficult for me… haha!

I see.
In addition, for Japanese people, simplified Chinese are more difficult than traditional Chinese.
(Japanese "漢字"'s glyph are similar to traditional Chinese characters.)

Anyway, Thank you very much!

**Comment by lhy2871** [comment]
About "检查更新". 检查更新=check update.
激活时检查更新=check update WHILE activate a license.
激活后检查更新=check update AFTER activate a license.
启动时检查更新=check update while starting up the app.

Wow, that's actually pretty amazing! We actually read Traditional Chinese kind of like you read them, they look a lot like Simplified Chinese. The difference is that we can probably understand 90% of the meaning of traditional Chinese without any translation tools.
When we were in school, our teachers discussed with us about how traditional Chinese characters actually reflect Chinese culture better. However, in order to make more poor people learn quickly, the Chinese characters had to be simplified to make it easier for people who have no basic knowledge of writing Chinese characters at all to learn.
What I am doing now is to honor my ancestors and respect the Chinese characters. It is also a way to make more and better software available to people who can only understand Chinese. Last but not least, I also hope that excellent software can be used by more people, and that the influence of excellent software like FastCopy can be expanded. (It's easier to collect money after expanding the influence~)

Thank you very much for making the excellent software FastCopy!
I usually write about simple software, but "用爱发电" (love-driven work) is not a long-term solution.
I hope you will continue to maintain this software and also wish you riches.

Hanyuan

**Comment by lhy2871** [comment]
I don't think there's much more I want to say in this discussion. You can close this issuse after you see my message.
If you want to continue to do more localization for FastCopy, maybe consider a more convenient way of collaboration.
For example, writing the translations as XML files, so that we can submit PRs specifically for the translation files after we've translated them.
This is how Unraid.net works for the translations I'm involved in: https://github.com/unraid/lang-zh_CN

Hanyuan Liu

**Comment by shirouzu** [comment]
Ok, I see.
Thank you for your contribution!
