### ISSUE TITLE
Meaning of verify modes?

### ISSUE THREAD

**Issue by pstein** [FastCopyLab/FastCopy#218]
In "Main Settings"---->Verify options I have the choice between

a) Conventional Verify (which means from my point of view: Calculate hash value of destination file and compare it with source hash value
or
b.) Compare source and destination file byte-by-byte

Correct?

**Comment by shirouzu** [comment]
No, it is not.
https://fastcopy.jp/help/fastcopy_eng.htm#setting_verify

**Comment by pstein** [comment]
What means "verified"?

Verified against what?

How does FC check if the transfer was successful. FC needs a kind of "solution" or correct (hash) value.
If FC only "verifies" destination: How can FC know that the transfer was correct (for all bytes)?

**Comment by shirouzu** [comment]
In both cases, the hash values are verified by comparing them.
In both cases, the hash value on the dest side is calculated by reading dest again after writing is complete.

As for the hash value on the src side,
In the case of Normal verify, the hash value is calculated using the src data read for writing.
In the case of Perfect verify, the hash value is calculated by rereading the src data again, separately from the read data for writing.

In normal verification, src is read only once, so if there is a temporary data corruption (which can occur due to PCI bus errors, etc.) at that time, the error cannot be detected.
With Perfect verify, errors can be detected in such cases.

**Comment by pstein** [comment]
ok, thank you
