### ISSUE TITLE
slower than Windows copy

### ISSUE THREAD

**Issue by muratrd** [FastCopyLab/FastCopy#246]
hello,

I copied my 65 GB data from internal Seagate HDD drive to external KINGSTON SSD drive via USB 3.1 port.
it took 2 hours 40 minutes with regular Windows copy.
it took 2 hours 44 minutes with FastCopy ver 5.4.3.

I copied my 149 GB data from internal KINSTON SSD drive to external KINGSTON SSD drive via USB 3.1 port.
it took 5 hours 35 minutes with regular Windows copy.
it took 5 hours 45 minutes with FastCopy ver 5.4.3.

I copied my 109 GB data from internal KINSTON SSD drive to external KINGSTON SSD drive via USB 3.1 port.
it took 2 hours 10 minutes with regular Windows copy.
it took 1 hours 50 minutes with FastCopy ver 5.4.3.

**during all three copies ;**
-  Full Speed is selected
-  256 MB Buffer is selected
-  Nonstop is clicked
-  Verify is clicked
-  Estimate is not clicked

what a great performance !!
FastCopy ver 5.4.3. IS NOT FAST at all !!
FastCopy ver 5.4.3. is even slower than regular Windows copy.

why do you fake people?

murat r. demir

**Comment by shirouzu** [comment]
If you want to compare copy speeds, the conditions must be the same or it is meaningless.

> Verify is clicked

Explorer did not not verify, but FastCopy did.

Verifiying increases copy time by 1.5 to 2 times because the destination is re-read and verified.
Therefore, your report is completely pointless.

Also, posting a lot of the same content is called multi-posting and is bad manners.
Furthermore, making foul-mouthed accusations is also bad manners.

I strongly recommend that you do not use FastCopy and never post on this forum again.
