### ISSUE TITLE
Retention of all file metadata 

### ISSUE THREAD

**Issue by fsalfen** [FastCopyLab/FastCopy#298]
**Question**
 Does FastCopy preserve all file metadata when copying or moving any kind or sort of files? This includes all image EXIF data contained in image files. Audio files fields such as Artist, Bit Rate, etc. Office Apps formats with Date, File Creation Date, File Modification Date, etc?? Of course, this includes file attributes as well.

Thank you in advance, Jaci (Forrest)

**Comment by a-raccoon** [comment]
Yes. FastCopy was the first Windows copy software that preserved File Creation dates, which is why it's so popular even 20 years later, it preserves File Modification dates too.

All in-file metadata is naturally preserved (EXIF, ID3 tags, etc) because file contents are copied exactly.

Extra metadata that you added via Windows Explorer are preserved with AltStream checked. (ADS; alternate data streams). But only if the source and target drives are NTFS formatted, not FAT/exFAT.

The file attributes Read-Only, Hidden, System, No Index Contents, etc are preserved, but not the Archive attribute which is always set to On at the destination.

File access control and ownership information is preserved when ACL is checked.  You might not want this, as it might prevent other people from reading the data on another machine without taking administrative ownership first.

Copying from NTFS to FAT volumes may cause your timestamps to round to the nearest 2-seconds (even number) because those filesystems use different timestamp resolutions. That is a permanent change to the timestamps even if you copy the files back to an NTFS volume.

**Comment by shirouzu** [comment]
Thank you for your comment! > a-raccoon-san
