### ISSUE TITLE
Shell Extension: File Explorer, Drag & Drop

### ISSUE THREAD

**Issue by BossSay** [FastCopyLab/FastCopy#306]
**Describe the bug**
- Drag & Drop doesn't work.

i.e. The attached screenshot exemplifies that right-click dragging & dropping a folder in File Explorer to the desktop does nothing...

- Enable the Shell Extension in Fast Copy (issue occurs in both standard & elevated)
- Select a Folder or File in File Explorer
- Drag & Drop

Result:
- A blank Fast Copy window, not populated with the paths.

**Version/Environment**
 - FastCopy ver5.7.10
 - Windows 11 Pro, 23H2, build: 22631.3527

![image](https://github.com/FastCopyLab/FastCopy/assets/95376842/f8f885e3-a742-4be4-a050-e40e1c5eb671)

**Comment by shirouzu** [comment]
Unfortunately I couldn't reproduce it.
Could you please show me the operation in a movie (ScreenToGif or etc), after restarting the OS?

**Comment by BossSay** [comment]
https://github.com/FastCopyLab/FastCopy/assets/95376842/8ea194ff-866d-46c0-a99d-0805bfdcd48a

**Comment by BossSay** [comment]
![image](https://github.com/FastCopyLab/FastCopy/assets/95376842/6fbd9572-46ba-4cb4-b332-e1bee63910fa)

**Comment by shirouzu** [comment]
Thank you!
But still I couldn't reproduce it...

I apologize for the inconvenience, but could you please confirm from which version the problem is occurring?
(Please note that you will need to log in again to update the shell extension)
https://github.com/FastCopyLab/FastCopyDist2

P.S I think it's better to use the dichotomy/bisect method. (v1 is ok and v11 is NG → then test v5, and if v5 is OK, then test v7 and if v7 is NG, then test v6)

**Comment by BossSay** [comment]
Okay, will do soon. Have to go to work right now. Tnks!
