### ISSUE TITLE
disable update check

### ISSUE THREAD

**Issue by jerrymessina** [FastCopyLab/FastCopy#33]
I just installed V4.1.0.

It seems that disabling the update check at startup is no longer working.
I've unchecked 'Misc settings | Update Check at Startup' and the program still tries to connect.

**Comment by FastCopyLab** [comment]
Please use official bug template.
-----
**To Reproduce**
Steps to reproduce the behavior:
(and How to confirm to connect?)

**Version/Environment**
 - OS ver:

**Comment by jerrymessina** [comment]
Sorry.

**To Reproduce**
Steps to reproduce the behavior:
Running FastCopy.exe triggers a firewall alert - trying to open a connection to 104.18.30.182 port 80 (http)

I checked the file fastcopy2.ini and it has the setting updCheck="0"

**Version/Environment**
    fastcopy v4.1.0
    OS ver: win7 x64

**Comment by shirouzu** [comment]
FastCopy uses https://fastcopy.jp/fastcopy-update.dat to check for updates.
Currently, fastcopy.jp is "160.16.61.55" or "2001:e42:102:1506:160:16:61:55".
Since it is https, use port 443.

And I don't know anything about "104.18.30.182". (cloudflare?)
Isn't this a problem in your environment? (Virus check, etc.).

**Comment by jerrymessina** [comment]
Quite strange...

I uninstalled v4.1.0, reinstalled v4.0.5 and everything worked as you describe.
I then reinstalled v4.1.0 and it now works too... update check tries to connect to 160.16.61.55 port 443!
Must have been some hiccup on my end... sorry to have bothered you.

**Comment by shirouzu** [comment]
OK
