### ISSUE TITLE
How to verify each file after transfer (and not all files at once)?

### ISSUE THREAD

**Issue by tobwz** [FastCopyLab/FastCopy#330]
As I found out Fastcopy transfers at first all files and then (if enabled) verifies them.

I prefer an immediate verify after copy/move.

Is this possible?

Fastcopy should this offer as an user option.

Thank you

**Comment by shirouzu** [comment]
I don't want to implement a function to read data immediately after copying, because this may reduce the reliability of the verification (Avoid the effects of HDD/SSD hardware write cache).
However, in the future, I may add a function to interrupt data verification after a certain period of time (such as 10 seconds).
