### ISSUE TITLE
Fastcopy transfer file with permission from server to synology is different permission right

### ISSUE THREAD

**Issue by gein744** [FastCopyLab/FastCopy#344]
Fastcopy transfer file with permission from Windows server to synology is different permission right.
After copy the data ,when i check at Synology web is the permission is splitting to same user to 2 permission. but see at windows explorer is only 1.
![image](https://github.com/user-attachments/assets/091f391c-c87c-4e8a-bb03-d026825c10ce)
![image](https://github.com/user-attachments/assets/8c508a0a-24e8-4766-ab69-3170b14b56ea)

**Comment by shirouzu** [comment]
Please state the exact version of Windows.
ACL writing is set automatically using the BackupRead/BackupWrite API.
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-backupwrite
However, because this is an old API, it may not be possible to completely reproduce the issue.

**Comment by gein744** [comment]
Hi, Windows server 2012R2

**Comment by shirouzu** [comment]
It looks like a problem caused by the interaction between the ACL settings via the BackupRead/BackupWrite API (the ACL contents are a black box to programmers) and Synology (is it samba internally?).
Essentially, I think the only solution is to inform Synology that the ACL entries via the official MS API are being separated and have them fix it.

In the future, this may change if we do not use the BackupRead/BackupWrite API but instead read out individual ACL entries and set them one by one on the dest side, but at the moment there are no plans in place.
