### ISSUE TITLE
Verify Error Copying to NAS

### ISSUE THREAD

**Issue by ghost** [FastCopyLab/FastCopy#347]
**Question**
I am trying to copy data to my new NAS, but at the end, the verification fails, and the copied file is renamed. What could be causing this error? Interestingly, one file was successfully copied over initially, but when I tried again, the same file failed to copy.

**Remarks**
Here is the log:
[20241227-024843-0.log](https://github.com/user-attachments/files/18256710/20241227-024843-0.log)

The NAS is still in the synchronization state, but that shouldn't be an issue, should it? Additionally, the NAS lags behind the PC by one second. Could this time difference be related to the problem?

**Comment by shirouzu** [comment]
There could be various reasons for this, such as memory, network, or internal NAS issues, so it's difficult to generalize.
Also, the NAS time is (in principle) irrelevant to this issue.

**Comment by ghost** [comment]
Okay, but what can be extracted from the error log, or is the error log useless?

**Comment by shirouzu** [comment]
??
The error log would tell you that there were files that were copied but had corrupted data?

**Comment by ghost** [comment]
Well, obviously. I would have expected the developer of the program to be a bit more helpful in such a situation, but I guess I was wrong. There's nothing wrong with the file, the network, or the NAS, yet somehow FastCopy throws an error and Windows copy copies the file perfectly fine - 100% matching SHA256. Guess I'll just not use your program instead? Weird.

**Comment by shirouzu** [comment]
I also think that's a good choice for you. Good luck!

For your information, it's not easy to analyze problems with copying.

- Inside the storage device (non-volatile memory, RAM)
- Problems with PCIe communication (especially bus resets can cause problems)
- Data corruption in main memory/CPU cache/CPU calculations
- Data corruption on the network
- Driver bugs
- Software bugs

To determine where the problem is, you need to reproduce the problem many times (but there are many temporary problems that only occur with a low probability), replace some of the above, and check.

Or you may need to compare the normal file and the corrupted file sector by sector, and check whether a bus reset occurred in the event viewer during the copy.

I don't think anyone would expect free support to do these analyses. :-)

**Comment by ghost** [comment]
Yes, thank you! After using FastCopy for over two years, I finally listened to the community and switched to TeraCopy. Not only is it much faster, but it also works flawlessly for copying, hashing, and verifying over network-attached storages.

I understand that analyzing volatile data issues isn't easy, and I certainly didn't expect "free" technical support. I just thought an error log would at least provide some understandable and documented code, at least for the developer. However, it seems that the developer is either unwilling to document error codes or at least be friendly enough to point in the correct direction.

That said, I’m just happy I decided against buying a license a few weeks ago after two years of using FastCopy and instead switched to TeraCopy after our interaction.

Good luck! :-)
