### ISSUE TITLE
Issue copying permissions at root of folder

### ISSUE THREAD

**Issue by stephen9482** [FastCopyLab/FastCopy#35]
having an issue where i copy a directory from source to destination is doesn't copy the root permissions of a folder. Once I reach the sub-directories it copies the permissions correctly but never the root folder. Using other tools like robocopy the permissions get copied correctly.

Thanks

**Comment by a-raccoon** [comment]
Can you tell me which of these you are using?

```
Source: X:\Folder
DestDir: Y:\
```
or
```
Source: X:\Folder
DestDir: Y:\Folder
```
or are you using wildcards anywhere?

**Comment by stephen9482** [comment]
no wildcards - 

using the format 

Source: X:\Folder
DestDir: Y:\Folder

**Comment by shirouzu** [comment]
Please use this format.
-----
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (principle, latest ver) :
 - OS ver:

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by a-raccoon** [comment]
> using the format
> Source: X:\Folder
> DestDir: Y:\Folder

You must use the format
```
Source: X:\Folder
DestDir: Y:\
```
... to copy over the folder itself, with its ACL.  If the DestDir does NOT have an ending backslash then the behavior is to copy only the CONTENTS of the Source into the DestDir.  If the DestDir DOES have an ending backslash then the behavior is to copy the Source directory itself to that destination (plus all of its contents).  The directory itself has the ACL attached to it.

https://fastcopy.jp/help/fastcopy_eng.htm#backslash_behavior
