### ISSUE TITLE
i/o speed is flawed in ver 4.1 compared to 3.92

### ISSUE THREAD

**Issue by hd4fun** [FastCopyLab/FastCopy#42]
**Describe the bug**

ver 4.1 does not maintain copy speeds or not interfere with other apps

veeam agent and fastcopy ver 4.1
reduces veeam agent to about 2 MB/s

![image](https://user-images.githubusercontent.com/4211350/155072112-5d131a56-1189-4f5a-b4aa-5efebf33cf33.png)

ver 3.91
![image](https://user-images.githubusercontent.com/4211350/155072351-e880646a-f661-410b-bf12-0ff160d6c412.png)
keeps veeam agent at about 12 MB/s

ignore the 175 MB/s as it is reading from cache - it's the write speed that is affected

**Comment by shirouzu** [comment]
Please see.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Command line options and various settings**
Describes command line options and settings that have been changed from the standard.

**Version/Environment**
 - FastCopy ver (principle, latest ver) :
 - OS ver:

**Screenshots**
If applicable, add screenshots to help explain your problem.
