### ISSUE TITLE
Copy with verification issue

### ISSUE THREAD

**Issue by Greg1966** [FastCopyLab/FastCopy#94]
Hello,
When you choose to copy with verification, the time is counted together and is adulterated.
The result should stop at the end of the transfer and not be counted during a verification where there is no data transfer.
Nice to check it out with all the verification options.
Greetings from Poland !!!
You are the best !!!

Greetings from Poland :)

Gregory
dicom@interia.pl

**Comment by a-raccoon** [comment]
It is pretty messed up, no doubt.  FastCopy 3x was rather spot on, but 4x will estimate 38 hours for a copy+verify that ends up only taking 23 hours.  The problem is the program is estimating for "write" time but verify is a read-only operation.  Making every transfer at least 25~33% faster than estimated.

**Comment by shirouzu** [comment]
I will consider it.

**Comment by Greg1966** [comment]
Hello Friends :)
in new 4.1.7 this issue above is still present !!!.
In Win7x64 and Win10x64 carefully checked !!!
This appears to be independent of the operating system version.

Greetings to all the strong FastCopy team :)

Gregory
dicom@interia.pl
