### ISSUE TITLE
Advise create hash file for detect silent data destruction 

### ISSUE THREAD

**Issue by ug802** [FastCopyLab/FastCopy#98]
**Describe the solution you'd like**

For detect silent data destruction, i advise fastcopy creat a md5hash file  to the destDIR.

just like:

739f01eefc1413162a158bab01b2f052 *file1.txt
c514e4a2cc6ffb096a97f1f0f5b57144 *file2.txt
..............

support scrub the  distDIR files with this md5hash file after a few year by hand.

**Additional context**

<img src = 'https://s3.bmp.ovh/imgs/2022/07/04/ca25ffd81f1fa64c.png' />

**Comment by ug802** [comment]
just like TeraCopy

**Comment by ug802** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2022/07/04/5473fff3d76d5a68.png' />

**Comment by kyuningeng** [comment]
I found a good one.

It uses some of the features of fastcopy to check for file corruption!
I tried it and it worked!

I can check if a file I copied a few years ago with fastcopy is not corrupt as of today.

However, this assumes that you created a "secondary stream" a few years ago.
(Most of you didn't create a "secondary stream" a few years ago, so you can't compare the results with those of a few years ago.)

Try it!
(There is a manual inside. You can't just check it out out of the blue because it requires preparation!)

https://bit.ly/37rgI88
fccheck.zip Download

How to download" ● No login required! ●
Click the third button "Download" on the same line as "fccheck.zip" at the top of the opened page.

↓ Download is in progress ← ignore × to delete!

Download completed automatically ("fccheck.zip" is created in the download folder)
----------------------------------------------Japanens
いいものを見つけました

fastcopyの機能を一部利用してファイル破損チェックができます
試したらちゃんと動きました

fastcopyで数年前にコピーしておいたファイルが今日現在壊れていないか
チェックできます
但し、数年前に「副次ストリーム」を作っておいた前提です
（ほとんどの方は、数年前に「副次ストリーム」を作っておかなかったので、数年前とは
比較できませんが、、、、、、■今後数年後には比較できます！！！）

使ってみてください
（内部にマニュアルがあります。準備が必要なので、いきなりチェックはできません！）

https://bit.ly/37rgI88
fccheck.zip ダウンロード

「ダウンロード方法」●ログインは不要です！！●
開いたページの最上段の fccheck.zip ←と同じ行の右端から３つ目のボタン「ダウンロード」←クリック

↓ ダウンロードが進行中です ←無視 × で消す！！！

自動でダウンロード完了（ダウンロード・フォルダに「fccheck.zip」が作成される）

**Comment by ug802** [comment]
> I found a good one.
> 
> It uses some of the features of fastcopy to check for file corruption! I tried it and it worked!
> 
> I can check if a file I copied a few years ago with fastcopy is not corrupt as of today.
> 
> However, this assumes that you created a "secondary stream" a few years ago. (Most of you didn't create a "secondary stream" a few years ago, so you can't compare the results with those of a few years ago.)
> 
> Try it! (There is a manual inside. You can't just check it out out of the blue because it requires preparation!)
> 
> https://bit.ly/37rgI88 fccheck.zip Download
> 
> How to download" ● No login required! ● Click the third button "Download" on the same line as "fccheck.zip" at the top of the opened page.
> 
> ↓ Download is in progress ← ignore × to delete!
> 
> Download completed automatically ("fccheck.zip" is created in the download folder) ----------------------------------------------Japanens いいものを見つけました
> 
> fastcopyの機能を一部利用してファイル破損チェックができます 試したらちゃんと動きました
> 
> fastcopyで数年前にコピーしておいたファイルが今日現在壊れていないか チェックできます 但し、数年前に「副次ストリーム」を作っておいた前提です （ほとんどの方は、数年前に「副次ストリーム」を作っておかなかったので、数年前とは 比較できませんが、、、、、、■今後数年後には比較できます！！！）
> 
> 使ってみてください （内部にマニュアルがあります。準備が必要なので、いきなりチェックはできません！）
> 
> https://bit.ly/37rgI88 fccheck.zip ダウンロード
> 
> 「ダウンロード方法」●ログインは不要です！！● 開いたページの最上段の fccheck.zip ←と同じ行の右端から３つ目のボタン「ダウンロード」←クリック
> 
> ↓ ダウンロードが進行中です ←無視 × で消す！！！
> 
> 自動でダウンロード完了（ダウンロード・フォルダに「fccheck.zip」が作成される）

thank you very much for comment.
i tried it and it  worked. but  i still want better.
 i still wish fastcopy creat a hash files in destdir ,that will not rely ntfs stream, then i can use more type hash checker like rapidcrc.

**Comment by kyuningeng** [comment]
So you want to use rapidcrc?

I tried it.

rapidcrc certainly seems to work!

But this is for a small number of files (folders).

You don't want to check the hash values of all the files on the HDD, do you?

**Comment by ug802** [comment]
fastcopy write hash md5 into ntfs stream ,but rapidcrc unicode can not readit.
so ,i think if fastcopy write a hash file into destdir will be better ,instead write into log.

**Comment by kyuningeng** [comment]
I see...that's how it is.

I want to use "rapidcrc unicode" at all costs! I hear you say.

I have been asked to make a hash file instead of a stream like this before.

Sadly, the author ignored it!

Maybe they thought, "Why do we have to write to another file when we are writing to the stream?

I don't like it! 

I think it will be ignored this time too, so I'm still going to use the

fccheck.zip

is the right answer!

You can start using it right away, today!

**Comment by ug802** [comment]
Teracopy can create a hash file.

 i think this function is necessary ,otherwise Teracopy will not Set the function  in a prominent location.

**Comment by kyuningeng** [comment]
Do you like Teracopy?

That would make the author mad again!
Use Teracopy!

That's the end of it. Maybe.

**Comment by ug802** [comment]
no ，i think fastcopy is better ,but i think the function is good too.

I like the logic of FastCopy

**Comment by kyuningeng** [comment]
Originally, "rapidCRC" can create MD5 files by itself, so there is no need to create MD5 files with fastcopy.

However, if "rapidCRC" creates an MD5 file at the time of copying with fastcopy, it is not necessary to create an MD5 file again.


The "rapidCRC" only checks for corruption, so it is more efficient.

Is that right?

Since you are trying to make fastcopy take over the MD5 file creation functionality of "rapidCRC", I'm sure the author will not like it.

**Comment by ug802** [comment]
for example i have 4T small files ,need copy to nas for backup(not ntfs filesystem).

if fastcopy create hash file,  then i dont need use rapidcrc create hash file again , that would save so much  time.

after a few years, i use some hashcheker (like rapidrcr) check For detect silent data destruction.

**Comment by kyuningeng** [comment]
You guessed it.

What is "not ntfs filesystem"?

Is it ext4 or something else?

Can you change that nas to ntfs filesystem?

**Comment by ug802** [comment]
i do not want change filesystem just for ntfs stream .
i just advise create a hashfiles.

**Comment by shirouzu** [comment]
I will consider it.
